package com.dndcharacters.s1project;

import java.awt.*;

public class Constants {
    /** Font object for labels */
    public static Font labels;
    /** Font object for buttons */
    public static Font buttons;
    /** Font for save button*/
    public static Font saveFont;

    public enum Races {
        Aarakocra,
        Aasimar,
        FallenAasimar,
        ProtectorAasimar,
        ScourgeAasimar,
        Bugbear,
        Bullywug,
        Centaur,
        Changeling,
        DEFAULT,
        Dhampir,
        Dragonborn,
        ChromaticDragonborn,
        DraconbloodDragonborn,
        GemDragonborn,
        MetallicDragonborn,
        RaveniteDragonborn,
        DuergarDwarf,
        HillDwarf,
        MarkOfWardingDwarf,
        MountainDwarf,
        DrowElf,
        EladrinElf,
        HighElf,
        MarkOfShadowElf,
        PallidElf,
        SeaElf,
        ShadarKaiElf,
        WoodElf,
        Fairy,
        Firbolg,
        AirGenasi,
        EarthGenasi,
        WaterGenasi,
        GithyankiGith,
        GithzeraiGith,
        Gnoll,
        DeepGnome,
        DeepSvirfneblinGnome,
        ForestGnome,
        MarkOfScribingGnome,
        RockGnome,
        Goblin,
        DankwoodGoblin,
        Goliath,
        Grimlock,
        Grung,
        HalfElf,
        AquaticHalfElf,
        DrowHalfElf,
        MarkOfDetectionHalfElf,
        MarkOfStormHalfElf,
        MoonHalfElf,
        SunHalfElf,
        WoodHalfElf,
        HalfOrc,
        MarkOfFindingHalfOrc,
        GhostwiseHalfling,
        LightfootHalfling,
        LotusdenHalfling,
        MarkOfHealingHalfling,
        MarkOfHospitalityHalfling,
        StoutHalfling,
        Harengon,
        Hexblood,
        Hobgoblin,
        Human,
        MarkOfFindingHuman,
        MarkOfHandlingHuman,
        MarkOfMakingHuman,
        MarkOfPassageHuman,
        MarkOfSentinelHuman,
        Kalashtar,
        Kenku,
        Kobold,
        Leonin,
        Lizardfolk,
        Locathah,
        Loxodon,
        Minotaur,
        Orc,
        Owlin,
        Reborn,
        Satyr,
        BeasthideShifter,
        LongtoothShifter,
        SwiftstrideShifter,
        WildhuntShifter,
        SimicHybrid,
        Skeleton,
        Tabaxi,
        Tiefling,
        AsmodeusTiefling,
        BaalzebulTiefling,
        DispaterTiefling,
        FiernaTiefling,
        GlasyaTiefling,
        LevistusTiefling,
        MammonTiefling,
        MephistophelesTiefling,
        DevilsTongueTiefling,
        HellfireTiefling,
        InfernalTiefling,
        WingedTiefling,
        ZarielTiefling,
        Tortle,
        Triton,
        Troglodyte,
        Vedalken,
        Verdan,
        Warforged,
        YuantiPureblood,
        Zombie
    }

    public enum Skills {
        Acrobatics,
        AnimalHandling,
        Arcana,
        Athletics,
        Deception,
        History,
        Insight,
        Intimidation,
        Investigation,
        Medicine,
        Nature,
        Perception,
        Performance,
        Persuasion,
        Religion,
        SleightOfHand,
        Stealth,
        Survival
    }

    public enum Alignment {
        LawfulGood,
        LawfulNeutral,
        LawfulEvil,
        NeutralGood,
        TrueNeutral,
        NeutralEvil,
        ChaoticGood,
        ChaoticNeutral,
        ChaoticEvil
    }

    public enum DamageTypes {
        Acid,
        Bludgeoning,
        Cold,
        Fire,
        Force,
        Lightning,
        Necrotic,
        Piercing,
        Poison,
        Psychic,
        Radiant,
        Slashing,
        Thunder
    }

    public enum Classes {
        Barbarian,
        Bard,
        Cleric,
        Druid,
        Fighter,
        Monk,
        Paladin,
        Ranger,
        Rogue,
        Sorcerer,
        Warlock,
        Wizard
    }

    public enum Ability {
        Strength,
        Dexterity,
        Constitution,
        Intelligence,
        Wisdom,
        Charisma
    }

    public enum CurrencyType {
        Copper,
        Silver,
        Electrum,
        Gold,
        Platinum
    }
}